/**
 * Organic Warm & Accessible Design System
 * Constants and sample data for Prompt Catalog
 */

import { CategoryConfig, Prompt } from '@/types';

export const CATEGORIES: Record<string, CategoryConfig> = {
  image: {
    id: 'image',
    label: 'Generazione Immagini',
    icon: '🎨',
    color: '#D97757',
    description: 'Prompt per generare immagini con AI',
  },
  text: {
    id: 'text',
    label: 'Testo & Scrittura',
    icon: '✍️',
    color: '#7B9E89',
    description: 'Prompt per generare e modificare testi',
  },
  strategy: {
    id: 'strategy',
    label: 'Strategia & Analisi',
    icon: '🎯',
    color: '#A89968',
    description: 'Prompt per analisi strategiche e pianificazione',
  },
};

export const SAMPLE_PROMPTS: Prompt[] = [
  {
    id: '1',
    title: 'Upscale e Restauro Immagini',
    content: 'Restore and enhance the provided image. Preserve original identity, facial structure, proportions and composition. High-fidelity photo restoration, ultra-realistic, natural skin texture, accurate details, professional photographic look. 4K output, sharp but natural focus, modern cinematic lighting, subtle volumetric lighting, professional color grading, depth of field, HDR. Shot on Arri Alexa, raw photo aesthetic, masterpiece.',
    category: 'image',
    promptType: 'positive',
    description: 'Restauro e upscale di immagini con preservazione dell\'identità originale',
    createdAt: new Date('2026-02-05'),
    updatedAt: new Date('2026-02-05'),
    tags: ['upscale', 'restauro', 'fotografia', 'qualità'],
  },
  {
    id: '2',
    title: 'Negative Prompt Persone',
    content: 'cartoon, 3d render, plastic skin, blur, smooth skin, painting, drawing, illustration, low quality, distorted eyes, asymmetrical face, bad anatomy, makeup, photoshop, airbrushed.',
    category: 'image',
    promptType: 'negative',
    description: 'Negative prompt per generazione di persone realistiche',
    createdAt: new Date('2026-02-05'),
    updatedAt: new Date('2026-02-05'),
    tags: ['negative', 'persone', 'realismo', 'fotografia'],
  },
  {
    id: '3',
    title: 'Macro Fotografia Estrema',
    content: 'Extreme macro close up of [FACIAL AREA / BODY PART]. Photorealistic detail with visible [PRIMARY TEXTURES eg pores, fine hairs, wrinkles, fibers]. Natural imperfections including [SUBTLE FLAWS eg redness, uneven tone, tiny blemishes]. Realistic surface variation with natural oil sheen and dryness in different areas. No makeup, no retouching.\n\nSurrounding skin shows authentic texture with visible pores, micro details, and natural asymmetry. Real skin translucency, no idealized smoothness.\n\nLighting is soft but directional, grazing the surface at a shallow angle to reveal texture and depth. Neutral white balance, true to life color science, cinematic contrast. No crushed blacks, no blown highlights. Ultra shallow depth of field with critical focus on the surface, gentle falloff toward the edges.\n\nShot on a high end macro lens, 100mm macro equivalent. Feels like a real DSLR or smartphone macro capture. Documentary realism, unretouched, raw and authentic. Not CGI.',
    category: 'image',
    promptType: 'positive',
    description: 'Fotografia macro estrema con dettagli realistici e texture autentiche',
    createdAt: new Date('2026-02-05'),
    updatedAt: new Date('2026-02-05'),
    tags: ['macro', 'fotografia', 'dettagli', 'realismo'],
  },
  {
    id: '4',
    title: 'Foto Profilo LinkedIn Professionale',
    content: 'A professional, high-resolution, profile photo, maintaining the exact facial structure, identity, and key features of the person in the input image. The subject is framed from the chest up, with ample headroom and negative space above their head, ensuring the top of their head is not cropped. The person looks directly at the camera, and the subject\'s body is also directly facing the camera. They are styled for a professional photo studio shoot, wearing a smart casual blazer. The background is a solid \'#141414\' neutral studio. Shot from a high angle with bright and airy soft, diffused studio lighting, gently illuminating the face and creating a subtle catchlight in the eyes, conveying a sense of clarity. Captured on an 85mm f/1.8 lens with a shallow depth of field, exquisite focus on the eyes, and beautiful, soft bokeh. Observe crisp detail on the fabric texture of the blazer, individual strands of hair, and natural, realistic skin texture. The atmosphere exudes confidence, professionalism, and approachability. Clean and bright cinematic color grading with subtle warmth and balanced tones, ensuring a polished and contemporary feel.',
    category: 'image',
    promptType: 'positive',
    description: 'Foto profilo LinkedIn professionale e di alta qualità',
    createdAt: new Date('2026-02-05'),
    updatedAt: new Date('2026-02-05'),
    tags: ['linkedin', 'profilo', 'professionale', 'fotografia'],
  },
  {
    id: '5',
    title: 'Sito Web per Agent AI',
    content: 'Agisci come Senior React Developer e UI/UX Designer specializzato in SPA statiche pronte al deploy su Vercel.\nDevi generare il codice completo di un sito web vetrina moderno, responsive e performante per una singola attività locale, utilizzando esclusivamente frontend.\n\nVincoli tecnici critici (non negoziabili):\n- Nessun backend: Vietato creare cartelle o file tipo server/, api/, express, middleware, funzioni serverless o SSR.\n- Stack obbligatorio: React 19 + Vite, Tailwind CSS 4, Shadcn/ui, React Router DOM, Lucide React.\n- Struttura progetto: Nella root (/) devono esserci: index.html, package.json, vite.config.ts, pnpm-lock.yaml, cartelle src/ e public/.\n- Build: Comando: pnpm build. Output: dist/.\n\nStruttura del sito (SPA con 2 route):\n- / – Homepage con Hero, Servizi, Social Proof, Footer\n- /chi-siamo – Storytelling, Valori, Punti di forza\n\nRequisiti: Mobile-First, Componenti riutilizzabili, Tailwind 4 e Shadcn/ui standard.',
    category: 'text',
    promptType: 'positive',
    description: 'Prompt per generare siti web moderni con React e deploy su Vercel',
    createdAt: new Date('2026-02-05'),
    updatedAt: new Date('2026-02-05'),
    tags: ['react', 'web', 'frontend', 'vercel', 'spa'],
  },
  {
    id: '6',
    title: 'Strategia Marketing Content',
    content: 'Agisci come un content marketer e analizza il mio account. Analizza i seguenti punti:\n\n1. Un elenco preciso di parole chiave rilevanti per la mia nicchia, almeno 30.\n\n2. Scrivi una descrizione per i Reels che risolva uno dei problemi reali della mia audience, quello che mi viene chiesto più spesso.\n\n3. Crea frasi che aumentino il coinvolgimento nei primi secondi dei Reels e aiutino il video a entrare nei consigliati.',
    category: 'strategy',
    promptType: 'positive',
    description: 'Analisi strategica per content marketing e Reels su Instagram',
    createdAt: new Date('2026-02-05'),
    updatedAt: new Date('2026-02-05'),
    tags: ['marketing', 'content', 'reels', 'strategia', 'seo'],
  },
  {
    id: '7',
    title: 'Script TikTok Virale IRONICO',
    content: 'Genera uno script TikTok altamente virale, basato su pattern interrupt, numeri specifici, storytelling ad alta ritenzione, tecniche di copywriting IRONICO e struttura psicolinguistica per watchtime e commenti.\n\nREGOLE PSICOLOGICHE:\n1. Cervello pigro: Prime 5–7 parole devono rompere uno schema mentale\n2. Pattern interrupt violento: Usa frasi che spiazzano\n3. Numeri ovunque: Ogni claim deve avere un numero specifico\n4. Visualizzazione assurda: Trasforma un concetto in immagine mentale estrema\n5. Soldi/tempo/sforzo: Percepire che il metodo fa risparmiare\n6. Timeline precisa: Non usare "presto", usare "14 giorni", "7 minuti"\n7. Eliminazione totale del rischio: Inserisci una garanzia psicologica\n8. Identità: Comunica che chi ascolta appartiene a un gruppo migliore\n\nFRAMEWORK IRONICO (7 elementi):\nI – Immediate Value (prime 5 parole potentissime)\nR – Rilevanza (parla SOLO al target)\nO – Oltraggio (affermazione sorprendente e vera)\nN – Numeri (dati ovunque)\nI – Irresistible Promise (risultato + meccanismo unico)\nC – Curiosity Gap (crea domanda)\nO – Open Loop (ogni parte apre la successiva)\n\nSTRUTTURA DELLO SCRIPT (50–60 secondi):\n1. HOOK (0-3 sec): 1 frase, pattern interrupt, numero, max 7 parole\n2. INTERESSE (4–10 sec): Perché devono ascoltarti?\n3. PROBLEMA (11–18 sec): Cosa fanno male, con numeri\n4. VISUALIZZAZIONE ASSURDA (19–23 sec): Immagine forte\n5. SOLUZIONE (24–35 sec): Nuovo metodo, semplice, numerico\n6. MICRO-PROVA (36–42 sec): Mini esempio concreto, numerico\n7. CTA (43–55 sec): Call to action a bassa frizione\n\nOUTPUT: Titolo (5 parole max), Script completo 50–60 sec, 3 alternative di hook',
    category: 'text',
    promptType: 'positive',
    description: 'Script TikTok virale con framework IRONICO e psicologia del copywriting',
    createdAt: new Date('2026-02-05'),
    updatedAt: new Date('2026-02-05'),
    tags: ['tiktok', 'script', 'viral', 'copywriting', 'marketing'],
  },
  {
    id: '8',
    title: 'Paesaggio Montano Cinematico',
    content: 'Create a breathtaking cinematic landscape of snow-capped mountains at sunset, with golden light reflecting off pristine snow, dramatic clouds, and a serene alpine lake in the foreground. Ultra-realistic, 8K resolution, professional photography style.',
    category: 'image',
    promptType: 'positive',
    description: 'Perfetto per generare sfondi e immagini di paesaggi montani',
    createdAt: new Date('2026-01-15'),
    updatedAt: new Date('2026-01-15'),
    tags: ['paesaggio', 'montagna', 'natura'],
  },
  {
    id: '9',
    title: 'Articolo Blog Professionale',
    content: 'Scrivi un articolo blog di 1500 parole su [TOPIC]. Lo stile deve essere professionale ma accessibile, con una struttura chiara (introduzione, 3-4 sezioni principali, conclusione). Includi esempi pratici e dati rilevanti. Tono: informativo e coinvolgente.',
    category: 'text',
    promptType: 'positive',
    description: 'Template per generare articoli blog di qualità',
    createdAt: new Date('2026-01-14'),
    updatedAt: new Date('2026-01-14'),
    tags: ['blog', 'articolo', 'scrittura'],
  },
  {
    id: '10',
    title: 'Analisi SWOT Strategica',
    content: 'Analizza [AZIENDA/PRODOTTO] con una matrice SWOT completa. Per ogni quadrante (Strengths, Weaknesses, Opportunities, Threats), fornisci 5-7 punti specifici e dettagliati. Includi raccomandazioni strategiche basate sull\'analisi.',
    category: 'strategy',
    promptType: 'positive',
    description: 'Prompt per analisi strategiche dettagliate',
    createdAt: new Date('2026-01-13'),
    updatedAt: new Date('2026-01-13'),
    tags: ['strategia', 'analisi', 'business'],
  },
  {
    id: '11',
    title: 'Personaggio Fantasy Dettagliato',
    content: 'Create a detailed fantasy character portrait: a mysterious elf sorceress with intricate magical tattoos, flowing ethereal robes, holding an ornate staff glowing with arcane energy. Mystical atmosphere, dramatic lighting, fantasy art style, highly detailed, 4K.',
    category: 'image',
    promptType: 'positive',
    description: 'Per creare personaggi fantasy dettagliati e affascinanti',
    createdAt: new Date('2026-01-12'),
    updatedAt: new Date('2026-01-12'),
    tags: ['fantasy', 'personaggio', 'arte'],
  },
  {
    id: '12',
    title: 'Email Marketing Persuasiva',
    content: 'Scrivi un\'email di marketing persuasiva per [PRODOTTO/SERVIZIO]. Struttura: subject line accattivante, opening hook, 3 benefici chiave, social proof/testimonial, CTA forte. Tono: conversazionale ma professionale. Lunghezza: 150-200 parole.',
    category: 'text',
    promptType: 'positive',
    description: 'Template per email marketing ad alta conversione',
    createdAt: new Date('2026-01-11'),
    updatedAt: new Date('2026-01-11'),
    tags: ['email', 'marketing', 'persuasione'],
  },
  {
    id: '13',
    title: 'Piano di Crescita Startup',
    content: 'Sviluppa un piano di crescita dettagliato per una startup nel settore [SETTORE]. Includi: target market, strategie di acquisizione, metriche KPI, timeline 12 mesi, budget allocation, rischi e mitigazioni.',
    category: 'strategy',
    promptType: 'positive',
    description: 'Framework per pianificare la crescita di startup',
    createdAt: new Date('2026-01-10'),
    updatedAt: new Date('2026-01-10'),
    tags: ['startup', 'crescita', 'pianificazione'],
  },
];
